environment: platform
serviceName: kubeseal-ui

deployment:
  containers:
    - name: app
      image: ghcr.io/kuvi-99/kubeseal-ui:1
      imagePullPolicy: Always
      ports:
        - name: http
          containerPort: 8080
      env:
        - name: SEALED_SECRETS_CONTROLLER_URL
          value: "http://sealed-secrets-controller.sealed-secrets.svc.cluster.local:8080/v1/cert.pem"
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 30

service:
  enabled: true
  port: 80
  targetPort: http

gateway:
  enabled: true
  profile: private
  hosts:
    - kubeseal.local.tlboos.com

pdb:
  enabled: false
